Neos:
  Neos:
    fusion:
      autoInclude:
        Ujamii.MailjetSubscription: true
    userInterface:
      translation:
        autoInclude:
          'Ujamii.MailjetSubscription': [ 'NodeTypes/*' ]

  Form:
    presets:
      default:
        finisherPresets:
          'Ujamii.MailjetSubscription:Form.MailjetSubscriptionFinisher':
            implementationClassName: Ujamii\MailjetSubscription\Form\Finisher\MailjetSubscriptionFinisher
          'Ujamii.MailjetSubscription:Form.MailjetCancellationFinisher':
            implementationClassName: Ujamii\MailjetSubscription\Form\Finisher\MailjetCancellationFinisher
